//MOT DE PASSE  AUTH ACTION
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const LOGOUT = "LOGOUT";

//Alert action
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
//INFERMIER ACTION
export const ADD_INFERMIER = "ADD_INFERMIER";
export const DELETE_INFERMIER = "DELETE_INFERMIER";
export const UPDATE_INFERMIER = "UPDATE_INFERMIER";
export const SAVE_INFERMIER = "SAVE_INFERMIER";
export const CLEAR_INFERMIER = "CLEAR_INFERMIER";
export const INFERMIER_ERROR = "INFERMIER_ERROR";
export const REMOVE_CURRENT_INFERMIER = "REMOVE_CURRENT_INFERMIER";
export const GET_INFERMIER = "GET_INFERMIER";
export const INFERMIER_INFOS = "INFERMIER_INFOS";
//patient action
export const GET_PATIENT = "GET_PATIENT";
export const GET_PATIENT_INF = " GET_PATIENT_INF";
export const ADD_PATIENT = "ADD_PATIENTPATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const SAVE_PATIENT = "SAVE_PATIENT";
export const CLEAR_PATIENT = "CLEAR_PATIENT";
export const PATIENT_ERROR = "PATIENT_ERROR";
export const REMOVE_CURRENT_PATIENT = "REMOVE_CURRENT_PATIENT";
//Action Suivie
export const ADD_SUIVIE = "ADD_SUIVIE";
export const GET_SUIVIE = "GET_SUIVIE";
export const SUIVIE_ERROR = "SUIVIE_ERROR";
//Action soin
export const ADD_SOIN = "ADD_SOIN";
export const GET_SOIN = "GET_SOIN";
export const SOIN_ERROR = "SOIN_ERROR";
//Action prescription
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const GET_PRESCRIPTION = "GET_PRESCRIPTION";
export const PRESCRIPTION_ERROR = "PRESCRIPTION_ERROR";
//action testCovid
export const ADD_TESTCOVID = "ADD_TESTCOVID";
export const GET_TESTCOVID = "GET_TESTCOVID";
export const TESTCOVID_ERROR = "TESTCOVID_ERROR";
export const GET_ALL_MEDECIN = "GET_ALL_MEDECIN ";









